import type { ServicePlan } from "./types";

export const servicePlans: ServicePlan[] = [
  {
    id: "sanctuary-lite",
    name: "Sanctuary Lite",
    price: "2",
    billingCycle: "Monthly",
    storageLimit: "10",
    userLimit: "2",
    userCount: "842 users",
    conversionRate: "4.2%",
    activeSubscribers: "842",
    churnRate: "1.1%",
    mrr: "$1.7k",
    selectedFeatures: [
      "AI Heritage Synthesis",
      "HD Memory Storage",
      "Family Tree Mapping",
      "Voice Archive Export",
    ],
  },
  {
    id: "sanctuary-plus",
    name: "Sanctuary Plus",
    price: "3",
    billingCycle: "Monthly",
    storageLimit: "50",
    userLimit: "5",
    userCount: "312 users",
    conversionRate: "2.8%",
    activeSubscribers: "312",
    churnRate: "1.2%",
    mrr: "$936",
    selectedFeatures: [
      "AI Heritage Synthesis",
      "HD Memory Storage",
      "Family Tree Mapping",
      "Voice Archive Export",
      "Priority Support",
      "Biometric Authentication",
    ],
  },
  {
    id: "legacy-enterprise",
    name: "Legacy Enterprise",
    price: "Custom",
    billingCycle: "Yearly",
    storageLimit: "Unlimited",
    userLimit: "Unlimited",
    userCount: "94 accounts",
    conversionRate: "1.1%",
    activeSubscribers: "1,248",
    churnRate: "1.2%",
    mrr: "$3.7k",
    selectedFeatures: [
      "AI Heritage Synthesis",
      "HD Memory Storage",
      "Quantum Encryption",
      "White-Label Access",
      "Family Tree Mapping",
      "Voice Archive Export",
      "Priority Support",
      "Biometric Authentication",
    ],
  },
];

export const planFeatureOptions = [
  "AI Heritage Synthesis",
  "HD Memory Storage",
  "Quantum Encryption",
  "White-Label Access",
  "Family Tree Mapping",
  "Voice Archive Export",
  "Priority Support",
  "Biometric Authentication",
];
